[package]
name = "rust_zero2prod"
version = "0.1.0"
edition = "2021"
author = "engr-uba -- Stephen Ezekwem <stephen.ezekwem@ezektec.com>"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

